services:
  card_ms:
    build: 
      context: ./Atomics/Card
      dockerfile: Card.Dockerfile
    ports:
      - '3001:3001'
    env_file:
      - .env.docker
    depends_on:
      - carddb
    networks:
      - esd-network

  wallet_ms:
    build: 
      context: ./Atomics/Wallet
      dockerfile: Wallet.Dockerfile
    ports:
      - '3002:3002'
    env_file:
      - .env.docker
    depends_on:
      - walletdb
    networks:
      - esd-network
  
  carddb:
    image: postgres:16
    ports:
      - '5432:5432'
    volumes:
      - ~/apps/card:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      - esd-network
  
  walletdb:
    image: postgres:16
    ports:
      - '5433:5432'
    volumes:
      - ~/apps/wallet:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      - esd-network

  tapin_composite:
    build:
      context: ./CompositeServices/TapIn
      dockerfile: TapIn.Dockerfile
    ports:
      - '4001:4001'
    env_file:
      - .env.docker
    depends_on:
      - card_ms
      - wallet_ms
    networks:
      - esd-network

  manage_incomplete_composite:
    build:
      context: ./CompositeServices/ManageIncomplete
      dockerfile: ManageIncomplete.Dockerfile
    ports:
      - '4002:4002'
    env_file:
      - .env.docker
    depends_on:
      - wallet_ms
    networks:
      - esd-network

  tapout_composite:
    build:
      context: ./CompositeServices/TapOut
      dockerfile: TapOut.Dockerfile
    ports:
      - '4003:4003'
    env_file:
      - .env.docker
    depends_on:
      - card_ms
      - wallet_ms
    networks:
      - esd-network

  auto_topup_composite:
    build:
      context: ./CompositeServices/AutoTopup
      dockerfile: AutoTopup.Dockerfile
    ports:
      - '4004:4004'
    env_file:
      - .env.docker
    depends_on:
      - wallet_ms
    networks:
      - esd-network

networks:
  esd-network:
    driver: bridge