services:
  card_ms:
    build: 
      context: ./Atomics/Card
      dockerfile: Card.Dockerfile
    ports:
      - '3001:3001'
    env_file:
      - .env.docker
  wallet_ms:
    build: 
      context: ./Atomics/Wallet
      dockerfile: Wallet.Dockerfile
    ports:
      - '3002:3002'
    env_file:
      - .env.docker
  
  carddb:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres